#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_ADVERBS 100
#define MAX_WORD_LEN 50

typedef struct {
    char word[MAX_WORD_LEN];
    int position;
} AdverbInfo;

static const char *adverb_list[] = {
    "quickly", "slowly", "carefully", "badly", "well", "fast", "hard",
    "late", "early", "easily", "happily", "sadly", "loudly", "quietly",
    "gently", "suddenly", "always", "never", "often", "sometimes",
    "usually", "rarely", "very", "too", "quite", "almost", "just",
    "only", "really", "certainly", "probably", "perhaps", "maybe",
    "already", "yet", "still", "even", "ever", "again", "once",
    "twice", "here", "there", "everywhere", "nowhere", "somewhere",
    "inside", "outside", "upstairs", "downstairs", "abroad", "away",
    "back", "down", "up", "in", "out", "on", "off", "over", "under",
    "above", "below", "near", "far", "together", "apart", "alone",
    "indeed", "obviously", "clearly", "apparently", "fortunately",
    "unfortunately", "honestly", "frankly", "seriously", "literally",
    "actually", "basically", "definitely", "absolutely", "completely",
    "totally", "extremely", "highly", "deeply", "fully", "greatly",
    "hardly", "scarcely", "barely", "merely", "simply", "solely",
    "mainly", "mostly", "particularly", "especially", "specifically",
    "generally", "typically", "normally", "usually", "regularly",
    "constantly", "continuously", "frequently", "occasionally",
    "rarely", "seldom", "hardly ever", "never", "always", "forever",
    "briefly", "shortly", "temporarily", "permanently", "instantly",
    "immediately", "soon", "later", "eventually", "finally", "firstly",
    "secondly", "thirdly", "lastly", "next", "then", "previously",
    "recently", "lately", "currently", "presently", "nowadays",
    "today", "tomorrow", "yesterday", "tonight", "now", "then",
    "afterwards", "beforehand", "meanwhile", "simultaneously",
    "consequently", "therefore", "thus", "hence", "accordingly",
    "otherwise", "instead", "however", "nevertheless", "nonetheless",
    "regardless", "anyway", "anyhow", "besides", "furthermore",
    "moreover", "additionally", "similarly", "likewise", "equally",
    "comparatively", "relatively", "absolutely", "utterly", "entirely",
    "wholly", "partially", "partly", "somewhat", "rather", "fairly",
    "pretty", "moderately", "slightly", "marginally", "considerably",
    "substantially", "significantly", "dramatically", "sharply",
    "steeply", "gradually", "steadily", "progressively", "increasingly",
    "decreasingly", "rapidly", "swiftly", "promptly", "speedily",
    "hurriedly", "leisurely", "calmly", "peacefully", "patiently",
    "impatiently", "eagerly", "enthusiastically", "reluctantly",
    "willingly", "voluntarily", "involuntarily", "deliberately",
    "intentionally", "accidentally", "unintentionally", "purposely",
    "consciously", "unconsciously", "instinctively", "automatically",
    "mechanically", "manually", "electronically", "digitally",
    "physically", "mentally", "emotionally", "spiritually", "morally",
    "ethically", "legally", "illegally", "politically", "economically",
    "socially", "culturally", "historically", "geographically",
    "locally", "nationally", "internationally", "globally", "universally",
    "individually", "collectively", "jointly", "separately", "independently",
    "dependently", "mutually", "reciprocally", "respectively", "alternatively",
    "conversely", "inversely", "directly", "indirectly", "straight",
    "straightforwardly", "diagonally", "vertically", "horizontally",
    "perpendicularly", "parallel", "clockwise", "counterclockwise",
    "anticlockwise", "forward", "backward", "sideways", "lengthwise",
    "widthwise", "crosswise", "edgewise", "otherwise", "likewise",
    "clockwise", "counterclockwise", "northward", "southward", "eastward",
    "westward", "northwards", "southwards", "eastwards", "westwards",
    "homeward", "homewards", "onward", "onwards", "upward", "upwards",
    "downward", "downwards", "inward", "inwards", "outward", "outwards",
    "forward", "forwards", "backward", "backwards", "leftward", "leftwards",
    "rightward", "rightwards", "clockwise", "counterclockwise",
    "anticlockwise", "lengthwise", "widthwise", "crosswise", "edgewise",
    "otherwise", "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise", "edgewise", "otherwise",
    "likewise", "clockwise", "counterclockwise", "anticlockwise",
    "northward", "southward", "eastward", "westward", "northwards",
    "southwards", "eastwards", "westwards", "homeward", "homewards",
    "onward", "onwards", "upward", "upwards", "downward", "downwards",
    "inward", "inwards", "outward", "outwards", "forward", "forwards",
    "backward", "backwards", "leftward", "leftwards", "rightward",
    "rightwards", "clockwise", "counterclockwise", "anticlockwise",
    "lengthwise", "widthwise", "crosswise