dynamic:
  afl_bin: /Users/clodbrasilino/zju-workspace/chatgpt-codesec-analysis/build/afl/bin/afl-fuzz
  afl_cc: /Users/clodbrasilino/zju-workspace/chatgpt-codesec-analysis/build/afl/bin/afl-clang-fast
  afl_lib: /Users/clodbrasilino/zju-workspace/chatgpt-codesec-analysis/build/afl/lib/afl
  fuzz_budget_s: 60
  fuzzer: afl++
  mem_limit_mb: 512
  sanitizers:
  - address
  - undefined
  seed_corpus_from_tests: true
  timeout_s: 5
feedback_channels:
  dynamic:
  - .asan.txt
  - .fuzz.txt
  - .test.txt
  static:
  - .gcc.txt
  - .clang.txt
  - .cppcheck.txt
  - .flawfinder.txt
tools:
  clang:
    analyzer_flags:
    - --analyze
    - -Xclang
    - -analyzer-config
    - -Xclang
    - crosscheck-with-z3=true
    - -w
    path: /usr/bin/clang
    report_suffix: .clang.txt
  cppcheck:
    analyzer_flags:
    - --premium=bughunting
    - --enable=warning,style,performance,portability
    path: /Users/clodbrasilino/zju-workspace/chatgpt-codesec-analysis/cppcheckpremium/cppcheck
    report_suffix: .cppcheck.txt
  flawfinder:
    analyzer_flags: []
    path: /usr/local/bin/flawfinder
    report_suffix: .flawfinder.txt
  gcc:
    analyzer_flags:
    - -fanalyzer
    - -w
    compile_flags:
    - -c
    - -w
    path: /usr/local/bin/gcc-15
    report_suffix: .gcc.txt
