"""ASan-attributed round-0 fuzz findings: message breakdown (heal_0).

Backs the paper's "What fuzzing finds" sentence about ASan-attributed
memory errors at generation: scans every main-cell heal_0 .fuzz.txt report,
keeps line-level findings whose message mentions ASan, and breaks them down
by the ASan classification prefix (stack-overflow, heap-buffer-overflow,
FPE, BUS, use-after-free, ...).

Output: results/asan_heal0_breakdown.md
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
from src.analysis.channel_comparison import MODELS, SLUG, parse, SEV  # noqa: E402

R = REPO / "results"


def main() -> None:
    c: Counter = Counter()
    progs: Counter = Counter()
    for m in MODELS:
        d = REPO / "data" / "collected_code_6" / m / SLUG / "heal_0"
        for p in d.glob("problem-*.c"):
            for ln, sev, msg in parse(d / f"{p.stem}.fuzz.txt"):
                if sev in SEV and "ASan" in msg:
                    key = msg.split("(")[0].strip()
                    c[key] += 1
                    progs[p.stem] += 1
    total = sum(c.values())
    L = ["# ASan-attributed round-0 fuzz findings (heal_0, main cells)", "",
         "Line-level findings (severity high/medium/low, line > 0) in",
         "`heal_0/*.fuzz.txt` whose message mentions ASan, grouped by the",
         "ASan classification prefix. Seven main cells, 20,454 programs.", "",
         "| ASan class | findings |", "|---|---:|"]
    for k, v in c.most_common():
        L.append(f"| {k} | {v} |")
    L += [f"| **TOTAL** | **{total}** |", "",
          f"Distinct programs with >=1 ASan-attributed finding: "
          f"{len(progs)}.", "",
          "Generated by `src/analysis/asan_heal0_breakdown.py`.", ""]
    out = R / "asan_heal0_breakdown.md"
    out.write_text("\n".join(L) + "\n")
    print(f"written -> {out}")
    for k, v in c.most_common():
        print(f"  {v:3d}  {k}")
    print(f"total {total} findings on {len(progs)} programs")


if __name__ == "__main__":
    main()
