"""Cost ratios behind tab:rq3's Cost column (ok calls only, 200-task subset).

For each of the five toggle-verified models, full-gate cells:
  base  = main cell ledger, restricted to the 200-task vulnerable-prone
          subset (repair calls only -- the base ledgers record no
          generation calls);
  think = thinking cell ledger (subset by construction; its ledgers record
          generation AND repair calls).
Ledger rows with ok == false are excluded (failed calls carry no token
cost). Ratios: total completion tokens (think/base) and mean per-call
latency (think/base).

Output: results/rq3_cost_ratios.md
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
R = REPO / "results"
SUBSET_CSV = R / "vulnerable_subset.csv"
BASE_SLUG = "feedback-static+dynamic-r0-t1.0-p1.0"
THINK_SLUG = "feedback-static+dynamic-r1-t1.0-p1.0"
PAIRS = [
    ("deepseek-v4-pro", "DeepSeek V4 Pro"),
    ("openai-gpt56-sol", "GPT-5.6~Sol"),
    ("gemini-3-pro", "Gemini 3.1 Pro"),
    ("kimi-k3", "Kimi K3"),
    ("glm-5.1", "GLM-5.1"),
]


def subset_ids() -> set[int]:
    ids = set()
    with open(SUBSET_CSV) as f:
        for i, row in enumerate(csv.DictReader(f)):
            if i < 200:
                ids.add(int(row["problem_id"]))
    assert len(ids) == 200
    return ids


def scan(path: Path, task_filter: set[int] | None) -> tuple[int, float, int]:
    """(completion tokens, latency sum, ok calls) over one ledger."""
    comp = lat = n = 0
    with open(path) as f:
        for line in f:
            try:
                e = json.loads(line)
            except json.JSONDecodeError:
                continue
            if e.get("ok") is not True:
                continue
            t = e.get("task_id")
            if task_filter is not None and (
                    t is None or int(t) not in task_filter):
                continue
            comp += e.get("completion_tokens") or 0
            lat += e.get("latency_s") or 0.0
            n += 1
    return comp, lat, n


def main() -> None:
    ids = subset_ids()
    L = ["# RQ3 cost ratios: thinking vs non-thinking (full-gate cells, "
         "200-task subset)", "",
         "Ok ledger calls only (failed calls carry no token cost). Base =",
         "main-cell ledger restricted to the 200 subset task ids (repair",
         "calls only); thinking = thinking-cell ledger (generation + repair).",
         "Same quantities as the Cost column of the paper's tab:rq3:",
         "completion-token ratio and mean per-call latency ratio.", "",
         "| Model | base comp tok | think comp tok | token ratio | "
         "base s/call | think s/call | latency ratio |",
         "|---|---:|---:|---:|---:|---:|---:|"]
    for model, disp in PAIRS:
        bc, bl, bn = scan(R / model / f"{BASE_SLUG}.usage.jsonl", ids)
        tc, tl, tn = scan(R / f"{model}-thinking" / f"{THINK_SLUG}.usage.jsonl",
                          None)
        tr = tc / bc
        lr = (tl / tn) / (bl / bn)
        L.append(f"| {disp} | {bc:,} | {tc:,} | {tr:.2f}x | "
                 f"{bl/bn:.1f} | {tl/tn:.1f} | {lr:.2f}x |")
    L += ["", "The paper quotes these rounded to one decimal (e.g., "
          "DeepSeek 2.2x / 11.2x; GPT-5.6 1.7x / 4.3x; Gemini 1.0x / 2.5x;",
          "Kimi 2.6x / 10.3x; GLM-5.1 6.1x / 17.0x).", "",
          "Generated by `src/analysis/rq3_cost_ratios.py`.", ""]
    out = R / "rq3_cost_ratios.md"
    out.write_text("\n".join(L) + "\n")
    print(f"written -> {out}")
    for line in L:
        if "x |" in line:
            print(line)


if __name__ == "__main__":
    main()
